included:
  - Sources
  - Tests
analyzer_rules:
  - unused_import
  - unused_declaration
line_length: 80
identifier_name:
  excluded:
    - cr
    - ln
    - no
nesting:
  type_level: 2
type_body_length:
  warning: 100
  error: 120
