included:
  - Sources
  - Tests
analyzer_rules:
  - unused_import
disabled_rules:
  - identifier_name
line_length: 120
identifier_name:
  excluded:
    - cr
    - ln
    - no
nesting:
  type_level: 2
